<?php if (flashBag()->has('success')): ?>
    <div class="success">
        <p class="alert"><?= htmlspecialchars(flashBag()->get('success')) ?></p>
        <span class="bnt-close">x</span>
    </div>
<?php elseif (flashBag()->has('error')): ?>
    <div class="error">
        <p class="alert"><?= htmlspecialchars(flashBag()->get('error')) ?></p>
        <span class="bnt-close">x</span>
    </div>
<?php endif; ?>

<div class="form">
    <div class="form-edit">
        <form method="post" action="<?= htmlspecialchars(url('/admin/update-admin')) ?>">
            <input type="hidden" name="id" value="<?= htmlspecialchars($admin['id']) ?>">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" id="email" name="email" value="<?= htmlspecialchars($admin['email']) ?>" placeholder=" * Email" required>
            </div>
            <div class="form-group">
                <label for="role_id">Role</label>
                <select name="role_id" id="role_id" required>
                    <option value="" selected hidden>* Role</option>
                    <?php foreach ($roles as $role): ?>
                        <?php if ($admin['role_id'] === $role['id']): ?>
                            <option value="<?= htmlspecialchars($role['id']) ?>" selected><?= htmlspecialchars($role['type_project']) ?></option>
                        <?php else: ?>
                            <option value="<?= htmlspecialchars($role['id']) ?>"><?= htmlspecialchars($role['type_project']) ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="firstName">Prénom</label>
                <input type="text" id="firstName" name="firstName" value="<?= htmlspecialchars($admin['firstName']) ?>" placeholder=" * Prénom" required>
            </div>
            <div class="form-group">
                <label for="lastName">Nom</label>
                <input type="text" id="lastName" name="lastName" value="<?= htmlspecialchars($admin['lastName']) ?>" placeholder=" * Nom" required>
            </div>
            <?php if (auth()->superAdmin()): ?>
                <input type="submit" value="Enregistré" class="btn-form">
            <?php endif; ?>
        </form>
    </div>

    <div class="form-password">
        <form method="post" action="<?= htmlspecialchars(url('/my-profile/edit-password')) ?>">
            <input type="hidden" name="id" value="<?= htmlspecialchars($admin['id']) ?>">
            <div class="form-group">
                <label for="password_old">Ancien mot de passe</label>
                <input type="password" id="password_old" name="password_old" required>
            </div>
            <div class="form-group">
                <label for="password">Nouveau mot de passe</label>
                <div class="password-input-container">
                    <input type="password" id="password" name="password" required>
                    <div class="img-resize">
                    <span class="eye-toggle">
                        <img src="<?= $base_path ?>/asset/img/icon/eye-close.png" alt="logo" class="icon eye">
                    </span>
                    </div>
                </div>
            </div>
            <?php if (auth()->superAdmin()): ?>
                <input type="submit" value="Enregistré" class="btn-form">
            <?php endif; ?>
        </form>
    </div>

</div>
