<div class="dashboard">
    <?php if (flashBag()->has('success')): ?>
        <div class="success">
            <p class="alert"><?= flashBag()->get('success') ?></p>
            <span class="bnt-close">x</span>
        </div>
    <?php elseif (flashBag()->has('error')): ?>
        <div class="error">
            <p class="alert"><?= flashBag()->get('error') ?></p>
            <span class="bnt-close">x</span>
        </div>
    <?php endif; ?>


    <div class="my-project">
        <?php if ($user): ?>
            <h2><?= $user['firstName'] ?? 'Prénom non renseigné' ?> <?= $user['lastName'] ?? 'Nom non renseigné' ?></h2>
            <p><?= $user['email'] ?></p>
            <?php if (auth()->superAdmin()): ?>
                <a href="<?= url('/my-profile/edit?id='.$user['id']) ?>">Modifier les informations</a>

            <?php endif ?>
        <?php elseif ($admin): ?>
            <h2><?= $admin['firstName'] ?? 'Prénom non renseigné' ?> <?= $admin['lastName'] ?? 'Nom non renseigné' ?></h2>
            <p><?= $admin['email'] ?></p>
            <?php if (auth()->superAdmin()): ?>
                <a href="<?= url('/admin-profile?id='.$admin['id']) ?>">Modifier les informations</a>
            <?php endif ?>

        <?php endif ?>

        <table class="my-project-table">
            <caption>Projets</caption>
            <thead>
            <tr>
                <th scope="col">Projet</th>
                <th scope="col">Période</th>
                <th scope="col">Type</th>
                <th scope="col">Commentaire</th>
                <th scope="col">Snapshot</th>
                <th scope="col">Dashboard</th>
                <?php if(auth()->isAdmin()): ?>
                    <th scope="col">Action</th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($projects as $project): ?>
                <tr>
                    <td data-label="Projet">
                        <a href="<?= url('/project?id='. $project['id']) ?>"> <?= $project['name'] ?></a>
                    </td>
                    <td data-label="Période"><?= $project['period'] ?></td>
                    <td data-label="Type"><?= $project['type_project'] ?></td>
                    <td data-label="Commentaire"><?= $project['comment'] ?></td>
                    <td data-label="Snapshot"><a href="<?= $project['link_snapshot'] ?>" target="_blank">lien</a></td>
                    <td data-label="Dashboard"><a href="<?= $project['link_dashboard'] ?>" target="_blank">lien</a></td>
                    <?php if (auth()->superAdmin() || auth()->canEdit() == $project['type_id']) : ?>
                        <td data-label="Modifier">
                            <button class="toggle-form">Modifier</button>
                        </td>
                    <?php endif; ?>
                </tr>
                <tr class="form-row hidden">
                    <td colspan="7">
                        <form method="post" action="<?= url('/project/update') ?>">
                            <input type="hidden" name="id" value="<?= $project['id'] ?>">
                            <input type="text" name="name" placeholder="* Projet" class="form-control" pattern=".{3,}" title="Le nom du projet doit contenir au moins 3 caractères" value="<?= htmlspecialchars($project['name']) ?>" required>
                            <input type="date" name="periode" placeholder="Période" class="form-control" value="<?= htmlspecialchars($project['period']) ?>">
                            <input type="text" name="comment" placeholder="Commentaire" class="form-control" value="<?= htmlspecialchars($project['comment']) ?>">
                            <input type="text" name="link_snapshot" placeholder="Snapshot" class="form-control" value="<?= htmlspecialchars($project['link_snapshot']) ?>">
                            <input type="text" name="link_dashboard" placeholder="Dashboard" class="form-control" value="<?= htmlspecialchars($project['link_dashboard']) ?>">
                            <?php if (auth()->superAdmin() || auth()->canEdit() == $project['type_id']) : ?>
                                <input type="submit" value="Enregistré" class="btn-form">
                            <?php endif; ?>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>


    <div class="my-document">
        <table class="my-document-table">
            <caption>Documents</caption>
            <thead>
            <tr>
                <th scope="col">Document</th>
                <th scope="col">Projet</th>
                <th scope="col">Date</th>
                <th scope="col">PDF</th>
                <?php if(auth()->superAdmin()): ?>
                    <th scope="col">Action</th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($documents as $document): ?>
                <tr>
                <td data-label="Document"><?= $document['name'] ?></td>
                <td data-label="Projet"><?= $document['project_name'] ?></td>
                <td data-label="Date"><?= $document['period'] ?></td>
                <td data-label="PDF"><a href="<?= '../asset/documents/' . $document['document'] ?>" target="_blank"><?= $document['name'] ?></a></td>
                <?php if(auth()->superAdmin()): ?>
                    <td data-label="Modifier">
                        <button class="toggle-form">Modifier</button>
                    </td>
                        <div class="popup-container hidden" id="popup-container-<?= $document['id'] ?>">
                            <div class="popup" id="popup-<?= $document['id'] ?>">
                                <p>Êtes-vous sûr de vouloir supprimer le document : <?= $document['name'] ?> ?</p>
                                <div class="btn-container">
                                    <a href="<?= url('/dashboard') ?>" class="btn-cancel">Annuler</a>
                                    <a href="<?= url('/document/delete?document_id='.$document['id']) ?>" class="btn-confirm">Confirmer</a>
                                </div>
                            </div>
                        </div>
                    <tr class="form-row hidden">
                        <td colspan="5">
                            <form method="post" action="<?= url('/document/update') ?>" enctype="multipart/form-data">
                                <input type="hidden" name="id" value="<?= $document['id'] ?>">
                                <input type="text" name="name" value="<?= $document['name'] ?>" placeholder="* Nom" required>
                                <select name="project_id" required>
                                    <option value="" selected="selected" hidden="hidden">* Projet</option>
                                    <?php foreach ($projects as $project): ?>
                                        <?php if ($document['project_id'] === $project['id']): ?>
                                            <option value="<?= $project['id'] ?>" selected><?= $project['name'] ?></option>
                                        <?php else: ?>
                                            <option value="<?= $project['id'] ?>"><?= $project['name'] ?></option>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </select>
                                <input type="date" name="period" value="<?= $document['period'] ?>" placeholder="* Date" required>
                                <input type="submit" value="Enregistrer" class="btn-form">
                            </form>
                        </td>
                    </tr>

                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>


</div>
