<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/x-icon" href="../asset/img/logo.ico" />
    <!-- CSS -->
    <link rel="stylesheet" href="../asset/css/main.css">
    <!-- JS -->
    <script type="module" src="../asset/js/main.js"></script>
    <title>PH Portail</title>
</head>
<body>


<header class="header">
    <nav class="nav">
        <div class="img-resize">
                <span>
                    <img src="../asset/img/PHNudgeTransparent.png" alt="logo" class="logo-PH">
                </span>
        </div>
        <?php if (auth()->isAuthenticated()): ?>
            <div class="user">
                <div class="user-name">
                    <?php if (auth()->getFullName()): ?>
                        <p><?= auth()->getFullName() ?></p>
                    <?php else: ?>
                        <p><?= auth()->getEmail() ?></p>
                    <?php endif ?>
                    <a class="nav-link" aria-current="page" href="<?= url('/logout') ?>">Déconnexion</a>
                </div>
            </div>
        <?php endif ?>
    </nav>
</header>

    <div class="jumbotron-error">
        <div class="jumbotron-error-text">
            <h2>Page not found</h2>
            <p>Sorry, the page you are looking for could not be found.</p>
            <a href="<?= url('/') ?>" class="btn">Go to home</a>
        </div>

        <img src="../asset/img/404.svg" alt="Try and Adopt" class="img-responsive">

    </div>



</body>
</html>
