<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/x-icon" href="/portal-website/asset/img/logo.ico" />
    <!-- CSS -->
    <link rel="stylesheet" href="/portal-website/asset/css/main.css">
    <!-- JS -->
    <script type="module" src="/portal-website/asset/js/main.js"></script>
    <title>PH Portail</title>
</head>
<body>


<header class="header">
    <nav class="nav">
        <div class="img-resize">
                <span>
                    <img src="/portal-website/asset/img/PHNudgeTransparent.png" alt="logo" class="logo-PH">
                </span>
        </div>
        <?php if (auth()->isAuthenticated()): ?>
            <div class="user">
                <div class="user-name">
                    <?php if (auth()->getFullName()): ?>
                        <p><?= auth()->getFullName() ?></p>
                    <?php else: ?>
                        <p><?= auth()->getEmail() ?></p>
                    <?php endif ?>
                    <a class="nav-link" aria-current="page" href="<?= url('/logout') ?>">Déconnexion</a>
                </div>
            </div>
        <?php endif ?>
    </nav>
</header>
<div class="jumbotron-error">
    <div class="jumbotron-error-text">
        <h1>Error 500- Internal Server Error</h1>
        <p>We're sorry, something went wrong on our website. Our team is working to fix the issue, but in the meantime, you can try refreshing the page or contacting our support team for further assistance.</p>
        <p>Thank you for your patience and we apologize for any inconvenience caused.</p>
        <a href="<?= url('/') ?>" class="btn">Go to home</a>
    </div>

    <img src="/portal-website/asset/img/error.svg" alt="Try and Adopt" class="img-responsive">

</div>



</body>
</html>
