
<div class="form">
    <div class="form-forget-password">
        <?php if (flashBag()->has('error')): ?>
            <?= flashBag()->get('error') ?>
        <?php endif; ?>
        <h1>Mot de passe oublié</h1>
        <p>Veuillez entrer votre adresse e-mail pour réinitialiser votre mot de passe :</p>
        <form method="post" action="<?= url('/user/change-password') ?>">
            <label for="email">Adresse e-mail :</label>
            <input type="email" id="email" name="email" required><br><br>
            <input type="submit" value="Réinitialiser">
        </form>
    </div>
</div>
