
<?php if (flashBag()->has('error')): ?>
    <?= flashBag()->get('error') ?>
<?php endif; ?>
<div class="form">
    <div class="form-reset-password">
        <p>Veuillez entrer votre nouveau mot de passe :</p>
        <form method="post" action="<?= url('/user/update-password') ?>">
            <div class="form-group">
                <label for="password">Nouveau mot de passe :</label>
                <div class="password-input-container">
                    <input type="password" id="password" name="password" required>
                    <div class="img-resize">
                    <span class="eye-toggle">
                        <img src="<?= $base_path ?>/asset/img/icon/eye-close.png" alt="Afficher/Masquer le mot de passe" class="icon eye">
                    </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="password_confirm">Confirmer le mot de passe :</label>
                <div class="password-input-container">
                    <input type="password" id="password_confirm" name="password_confirm" required>
                    <div class="img-resize">
                    <span class="eye-toggle">
                        <img src="<?= $base_path ?>/asset/img/icon/eye-close.png" alt="Afficher/Masquer le mot de passe" class="icon eye">
                    </span>
                    </div>
                </div>
            </div>
            <input type="hidden" name="token" value="<?= $token ?>">
            <input type="submit" value="Réinitialiser">
        </form>
    </div>
</div>
