<?php if (flashBag()->has('error')): ?>
    <?= flashBag()->get('error') ?>
<?php endif; ?>
<div class="reset-password">
    <p>Veuillez entrer votre nouveau mot de passe :</p>
    <form method="post" action="<?= url('/user/update-password') ?>">
        <input type="hidden" name="id" value="<?= $id ?>">
        <label for="password">Nouveau mot de passe :</label>
        <input type="password" id="password" name="password" required><br><br>
        <label for="password_confirm">Confirmer le mot de passe :</label>
        <input type="password" id="password_confirm" name="password_confirm" required><br><br>
        <input type="submit" value="Réinitialiser">
    </form>
</div>
